### PR TITLE
Fix: Only emit `error` events when there is a listener (fixes #35)

### LINKED ISSUE #35: Crashes when an error occurs inside the callback & no error handlers are attached
Ref https://github.com/gulpjs/gulp/issues/2111 and the comments in #34 

It seems that this is a bug and it isn't likely that someone would rely on the "crashing" behavior (plus, it was never spec'ed by the tests). However, someone might want to attach an error listener and do something with the errors (outside of the gulp task system), so we should keep emitting errors.  We can guard against the crash behavior by looking up if there's any handlers for `'error'` and only emitting if any exist.

### PR DESCRIPTION
**Pull request by phated**
cc @contra @erikkemperman @th0r @stevelacy @gauntface 

Based on the feedback in the other PR (#34), do you all agree that this is actually a bug and should be fixed in the way presented in this PR?  I also described it in #35 but will quote that here:

> It seems that this is a bug and it isn't likely that someone would rely on the "crashing" behavior (plus, it was never spec'ed by the tests). However, someone might want to attach an error listener and do something with the errors (outside of the gulp task system), so we should keep emitting errors. We can guard against the crash behavior by looking up if there's any handlers for 'error' and only emitting if any exist.

### CODE REVIEW

File: test/index.js [hunk 1]
```diff
@@ -175,6 +175,18 @@ describe('glob-watcher', function() {
     watcher.on('ready', changeFile);
   });
 
+  it('does not emit an error (and crash) when no handlers attached', function(done) {
+    var expectedError = new Error('boom');
+
+    watcher = watch(outGlob, function(cb) {
+      cb(expectedError);
+      setTimeout(done, timeout * 3);
```
Comment (stevelacy) [inline test/index.js]: just wondering, what is the 3 for, could it be a different number and affect the result?

Comment (phated) [reply test/index.js]: No, it's just a conservative number - the test below uses `timeout * 3` also.

**Comment by erikkemperman** [comment]
LGTM!

**Comment by gauntface** [comment]
LGTM
